name: CI

on:
  push:
    branches:
      - '**'

jobs:  
  validate-release-name:
    name: Validate release name
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout working branch
        uses: actions/checkout@v1

      - name: Set environment variables
        run: |
          echo ::set-env name=BRANCH::$(git branch -r --contains ${GITHUB_SHA} | grep "")
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g" | sed -e "s/\//-/g")

      - name: Validate Release Tag
        if: "!github.event.release.prerelease"
        run: |
          MASTER_BRANCH_NAME='origin/master'
          RELEASE_PREFIX='r-'

          if [[ "${{ env.BRANCH }}" == *"$MASTER_BRANCH_NAME"* ]] && [[ "${{ env.RELEASE_VERSION }}" == "$RELEASE_PREFIX"* ]]; then
            echo "Release tag validation succeeded!"
            exit 0
          else
            echo "Release tag validation failed!"
            exit 1
          fi

      - name: Validate Pre-Release Tag
        if: "github.event.release.prerelease"
        run: |
          echo "Pre-release tag validation succeeded!"
          exit 0
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      herbie-db:
        image: postgres:12.1
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: herbie_db
        ports:
        - 5432:5432
      herbie-google-pub-sub:
        image: 'knarz/pubsub-emulator'
        ports:
          - '8085:8085'
    steps:

    - name: Checkout working branch
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev
