name: CI

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      herbie-db:
        image: postgres:12.1
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: herbie_db
        ports:
        - 5432:5432
      herbie-google-pub-sub:
        image: 'knarz/pubsub-emulator'
        ports:
          - '8085:8085'
    steps:

    - name: Checkout working branch
      uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev
